name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t next-app:latest .

      - name: Save Docker image to tar
        run: |
          docker save next-app:latest -o next-app.tar

      - name: Upload next-app.tar & docker-compose.yml
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          source: |
            next-app.tar
            docker-compose.yml

          target: /home/${{ secrets.EC2_USER }}/domain_scan
          overwrite: true
          rm: false

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/domain_scan

            docker load -i next-app.tar

            docker stop next-app || true
            docker rm next-app || true

            docker compose down || true
            docker compose up -d --build
