name: Deploy to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t next-app:latest .

      # 3. Save image to tar file
      - name: Save image as TAR
        run: |
          docker save -o next-app.tar next-app:latest

      # 4. Upload TAR + docker-compose.yml to EC2
      - name: Upload files to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          source: |
            next-app.tar
            docker-compose.yml

          target: /home/${{ secrets.EC2_USER }}/domain_scan
          overwrite: true
          rm: false

      # 5. Run container on EC2
      - name: Deploy on EC2 using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/domain_scan

            # Load Docker Image
            docker load -i next-app.tar

            # Stop existing container
            docker stop next-app || true
            docker rm next-app || true

            # Start using docker-compose
            docker compose up -d --force-recreate
